# CONFIG_.yaml



METADATA:
  SPANISH:
    'Author': 'Ibon Mart칤nez-Arranz (@imarranz)'
    'Title': 'Epidemia de C칩lera en Londres'
    'Subject': 'Epidemia de C칩lera en Londres'
    'Keywords': 'John Snow'
  ENGLISH:
    'Author': 'Ibon Mart칤nez-Arranz (@imarranz)'
    'Title': 'Cholera Epidemic in London'
    'Subject': 'Cholera Epidemic in London'
    'Keywords': 'John Snow'


# NIMAGES
# Definimos el n칰mero de im치genes con las que vamos a trabajar
# Normalmente ser치n ocho.

NIMAGES: 8

# BOXCOLOR
# Definimos el color de la caja de texto

BORDERCOLOR:
  - 79
  - 79
  - 79

BOXCOLOR:
  - 245
  - 234
  - 208

# IMAGES
# Definimos el nombre de las im치genes sobre las que vamos a procesar el texto

IMAGES:
  - "John_Snow_01.webp"
  - "John_Snow_02.webp"
  - "John_Snow_03.webp"
  - "John_Snow_04.webp"
  - "John_Snow_05.webp"
  - "John_Snow_06.webp"
  - "John_Snow_07.webp"
  - "John_Snow_08.webp"

# TEXTS
# Definimos los textos, en castellano y en ingl칠s, que ir치n en las figuras. Son dos listas con cadenas
# de texto, tantas cadenas como im치genes queramos procesar. Una lista contiene los textos en castellano
# y la otra lista contiene los textos en ingl칠s

TEXTS:
  SPANISH:
    - "John Snow, el precursor de la epidemiolog칤a moderna, en su estudio."
    - "Escena de la calle londinense de 1850, vibrante y llena de vida cotidiana."
    - "Londres enfrenta un grave brote de c칩lera, mostrando la urgencia y el desaf칤o."
    - "John Snow investiga el brote, observando meticulosamente las condiciones."
    - "Snow marca un mapa del c칩lera, utilizando datos para buscar patrones."
    - "La bomba de agua de Broad Street identificada como la fuente del c칩lera."
    - "Snow remueve la manija de la bomba, una decisi칩n crucial para detener el brote."
    - "El legado de Snow altera permanentemente la salud p칰blica y la epidemiolog칤a."


  ENGLISH:
    - "John Snow, the forerunner of modern epidemiology, in his study."
    - "A bustling 1850 London street scene, vibrant with everyday life."
    - "London faces a severe cholera outbreak, showcasing the urgency and challenge."
    - "John Snow investigates the outbreak, meticulously observing the conditions."
    - "Snow marks a cholera map, using data to search for patterns."
    - "The Broad Street water pump identified as the source of cholera."
    - "Snow removes the pump handle, a crucial decision to stop the outbreak."
    - "Snow's legacy permanently alters public health and epidemiology."

LINKEDIN:
    SPANISH: |
        游댌游깴 Innovaci칩n en la Salud P칰blica: John Snow y la Epidemia de C칩lera 游깴游댌

        En 1854, Londres fue azotada por una devastadora epidemia de c칩lera. John Snow, considerado el padre de la epidemiolog칤a moderna, realiz칩 un trabajo pionero que cambi칩 nuestra comprensi칩n de las enfermedades transmisibles. Mediante la meticulosa recolecci칩n de datos y el an치lisis de patrones de enfermedad, Snow identific칩 una bomba de agua en Broad Street como la fuente del brote. Su decisi칩n de remover la manija de esta bomba se considera uno de los primeros ejemplos de intervenci칩n epidemiol칩gica. El trabajo de Snow no solo ayud칩 a terminar con el brote, sino que tambi칠n impuls칩 mejoras en los sistemas de agua potable, salvando innumerables vidas en el futuro.

        Esta historia no solo demuestra la importancia de la observaci칩n y el an치lisis estad칤stico en la salud p칰blica, sino que tambi칠n destaca el impacto duradero que una persona puede tener en la salud global.

        #Peque침asHistoriasDeEstad칤stica #Epidemiolog칤a #SaludP칰blica #JohnSnow #HistoriaDeLaMedicina

    ENGLISH: |
        游댌游깴 Public Health Innovation: John Snow and the Cholera Epidemic 游깴游댌

        In 1854, London was struck by a devastating cholera outbreak. John Snow, considered the father of modern epidemiology, undertook groundbreaking work that transformed our understanding of communicable diseases. Through meticulous data collection and disease pattern analysis, Snow pinpointed a water pump on Broad Street as the source of the outbreak. His decision to remove the handle of this pump is regarded as one of the earliest examples of epidemiological intervention. Snow's work not only helped to end the outbreak but also spurred improvements in drinking water systems, saving countless lives in the future.

        This story not only underscores the importance of observation and statistical analysis in public health but also highlights the lasting impact one individual can have on global health.

        #LittleTalesOfStatistics #Epidemiology #PublicHealth #JohnSnow #HistoryOfMedicine
